apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: full-cicd-pipeline
  namespace: pac-poc
spec:
  tasks:
    - name: test
      taskRef:
        name: test-task
    
    - name: build
      runAfter: ["test"]
      taskRef:
        name: build-task
    
    - name: deploy
      runAfter: ["build"]
      taskRef:
        name: deploy-task
