apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-on-comment
  namespace: pac-poc
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[master]"
    pipelinesascode.tekton.dev/on-comment: "^/build$"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineSpec:
    tasks:
      - name: run-build
        taskSpec:
          steps:
            - name: build
              image: registry.access.redhat.com/ubi8/ubi-minimal:latest
              script: |
                #!/bin/bash
                echo "==================================="
                echo "🔨 BUILDING APPLICATION"
                echo "==================================="
                echo "Compiling code..."
                sleep 2
                echo "Creating artifacts..."
                sleep 1
                echo "✅ Build completed successfully!"
