apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-cluster-pipeline
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[master]"
    pipelinesascode.tekton.dev/on-comment: "^/build-cluster$"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineRef:
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: build-pipeline
      - name: namespace
        value: pac-poc
