apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: full-cicd-on-comment
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-comment: "/run-all"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineRef:
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: full-cicd-pipeline
      - name: namespace
        value: pac-poc
