apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: full-cicd-on-comment
  namespace: pac-poc
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[master]"
    pipelinesascode.tekton.dev/on-comment: "^/run-all$"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineSpec:
    tasks:
      - name: test
        taskSpec:
          steps:
            - name: test
              image: registry.access.redhat.com/ubi8/ubi-minimal:latest
              script: |
                #!/bin/bash
                echo "==================================="
                echo "🧪 RUNNING TESTS"
                echo "==================================="
                echo "Running unit tests..."
                sleep 2
                echo "✅ All tests passed!"
      - name: build
        runAfter: ["test"]
        taskSpec:
          steps:
            - name: build
              image: registry.access.redhat.com/ubi8/ubi-minimal:latest
              script: |
                #!/bin/bash
                echo "==================================="
                echo "🔨 BUILDING APPLICATION"
                echo "==================================="
                echo "Compiling code..."
                sleep 2
                echo "Creating artifacts..."
                sleep 1
                echo "✅ Build completed successfully!"
      - name: deploy
        runAfter: ["build"]
        taskSpec:
          steps:
            - name: deploy
              image: registry.access.redhat.com/ubi8/ubi-minimal:latest
              script: |
                #!/bin/bash
                echo "==================================="
                echo "🚀 DEPLOYING APPLICATION"
                echo "==================================="
                echo "Deploying to environment..."
                sleep 2
                echo "Running health checks..."
                sleep 1
                echo "✅ Deployment successful!"
